# Generated by Django 3.0.7 on 2020-06-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200527_2321'),
        ('carts', '0006_remove_cart_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(blank=True, to='products.Item'),
        ),
    ]
