# Generated by Django 3.2.3 on 2021-05-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210525_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=12.2, max_digits=100, null=True),
        ),
    ]
