# Generated by Django 3.0.4 on 2020-05-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('text', models.TextField()),
                ('slug', models.SlugField(default=models.TextField(max_length=50))),
                ('price', models.FloatField()),
                ('dis_price', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('S', 'SHIRT'), ('TS', 'T-SHIRT'), ('P', 'PANTS')], max_length=2)),
            ],
        ),
    ]
